name: XHM_CD

on:
  push:
    branches:
      - test_deploy

jobs:
  build:
    strategy:
      matrix:
        targetplatform: [x64]

    runs-on: self-hosted

    env:
      Solution_Path: ..\XemoHandleManagment.sln
      Project_Path: XemoHandleManagment.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    # Build app
    - name:  Build and publish app via ClickOnce
      run: dotnet msbuild -p:Configuration=$env:Configuration -p:OutputPath=$env:OutDir 
      env:
        Configuration: Release
        OutDir: ~\Regata\dev\XHM
        RuntimeIdentifier: win-${{ matrix.targetplatform }}

  