name: XHM_CD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: self-hosted

    env:
      ARTIFACTS: C:\actions-runner\apps\Core\Core\artifacts

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    # Build app
    - name:  Build
      run: dotnet build -c $env:Configuration
      env:
        Configuration: Release

      # Publish app
    - name:  Publish
      run: dotnet publish -c $env:Configuration  -o $env:OutDir --self-contained true -r win10-x86
      env:
        Configuration: Release
        OutDir: C:\REGATA\XHM\
  
