name: XHM_CD

on:
  push:
    branches:
      - test_deploy

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    # Build app
    - name:  Build and publish app via ClickOnce
      run: dotnet build -c $env:Configuration
      env:
        Configuration: Release
  