name: XHM_CD

on:
  push:
    branches:
      - test_deploy
#  pull_request:
#    branches:
#      - master

jobs:

  build:

    strategy:
      matrix:
        targetplatform: [x86]

    runs-on: self-hosted

    env:
      Solution_Path: ..\XemoHandleManagment.sln
      Project_Path: XemoHandleManagment.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    # Build app
    - name:  Restore the application to populate the obj folder
      run: dotnet msbuild .\XemoHandleManagment.sln  -p:Configuration=$env:Configuration;OutDir=$env:OutDir 
      env:
        Configuration: Release
        OutDir: ~\Regata\dev\XHM
        RuntimeIdentifier: win-${{ matrix.targetplatform }}

  